build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest
  armhf: ghcr.io/home-assistant/armhf-base:latest
  i386: ghcr.io/home-assistant/i386-base:latest
labels:
  org.opencontainers.image.title: "SSH Reverse Tunnel"
  org.opencontainers.image.description: "Expose Home Assistant via persistent SSH reverse tunnel."
  org.opencontainers.image.source: "https://example.com/ssh_reverse_tunnel"
  org.opencontainers.image.licenses: "MIT"
